# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "X", # <fcstat.sel>
  "hatOmega", # <fcstat.sel>
  "base", # <fcstat.sel>
  "method", # <fcstat.sel>
  "lambda", # <fcstat.sel>
  "target", # <fcstat.sel>
  "initial", # <fcstat.sel>
  "utilopt", # <fcstat.sel>
  "score", # <fcstat.sel>
  NULL
))
